site_name: Pasadena's Site
theme:
  name: material

  custom_dir: overrides

  palette: 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: deep purple
      accent: deep purple

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: deep purple
      accent: deep purple

  features:
    - navigation.instant
    # navigation.tracking / anchor tracking is the setting that automatically
    # updates the URL when scrolling
    # - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    # - announce.dismiss  # only add if you have an announcement, otherwise it
                          # only shows a blank announcement bar
    - content.action.edit
    - content.action.view

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
  # - offline

nav:
  - Home: https://upasadena.github.io/
  - CYOAs: https://upasadena.github.io/cyoas/
  - Interactive CYOA Tutorial:
    - index.md
    - Introduction:
      - introduction/index.md
    - Basics:
      - basics/index.md
    - Mechanics:
      - mechanics/index.md
      - Rows: mechanics/rows.md
      - Objects / Choices: mechanics/objects.md
      - IDs & Requirements: mechanics/ids-and-requirements.md
    - Styling:
      - styling/index.md
    - Publishing:
      - publishing/index.md
      - Static: publishing/static.md
      - Github: publishing/github.md
      - Neocities: publishing/neocities.md
    - Extending Your CYOA:
      - extending-your-cyoa/index.md
    - Reference:
      - reference/index.md
    - About:
      - about/index.md

extra:
  social:
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/user/_pasadena
      name: _pasadena on Reddit
    - icon: fontawesome/brands/github
      link: https://github.com/upasadena
      name: upasadena on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/h9txkD2Tcc
      name: Pasadena's discord server

copyright: The source code of this website is subject to the <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPLv3 licence</a>.<br>The content of this website is subject to the <a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt">CC BY-SA 4.0 licence</a>.

repo_url: https://github.com/upasadena/interactive-cyoa-tutorial
repo_name: upasadena/interactive-cyoa-tutorial
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr # use abbreviations, like hovertext
  - admonition # note boxes
  - attr_list # add html and css attributes to most stuff
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list # definitions like MediaWiki
  - footnotes # footnotes
  - md_in_html # allow use of markdown in html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - tables # must
  - pymdownx.caret # insert, superscript
  - pymdownx.mark # highlighting
  - pymdownx.tilde # delete, subscript
  - pymdownx.details # collapsable note boxes for admonition
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - overrides/
  - includes/

extra_javascript:
  - js/extra.js
  - js/moment-with-locales.js