name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clone
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      # Weekly cache
      # - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        id: cache-venv
        with:
          # key: mkdocs-material-${{ env.cache_id }}
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          # Was: .cache
          path: ./.venv/
          restore-keys: |
            ${{ runner.os }}-venv-
      - run: python -m venv ./.venv && . ./.venv/bin/activate &&
             pip install -r ./requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: . ./.venv/bin/activate && mkdocs gh-deploy --force
