name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV # (3)!
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      # - run: pip install mkdocs-material # (4)!
      - run: git clone --depth 1 -b 9.2.0b0 https://github.com/squidfunk/mkdocs-material/
      # - run: cd mkdocs-material
      - run: pip install -e ./mkdocs-material/
      # - run: cd ..
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: mkdocs gh-deploy --force